### ISSUE TITLE
Support more token signing algorithms

### ISSUE THREAD

**Issue by Allsimon** [navikt/mock-oauth2-server#121]
Hello,

is it possible to support more token signing algorithms? It looks like only RS256 is supported out of the box

**Comment by tommytroen** [comment]
@Allsimon It can be done yes, which algorithms are you looking to use?

**Comment by Allsimon** [comment]
I'd like to use RS512 and ES256

**Comment by tommytroen** [comment]
@Allsimon We will put it in the backlog 👍
