### ISSUE TITLE
Feature Request: REST endpoint on Standalone server to define JSON_CONFIG

### ISSUE THREAD

**Issue by git9999999** [navikt/mock-oauth2-server#194]
Hi

I am just started with Oauth2 and am sorry if my text contain some errors :-( and I am not sure if i under stud all concepts right.

I have a Project that has a System Test. In the System Test all apps are started in docker containers. The Test runs on public APIs of that containers and for some components i programmed some Mocks. I am able to generate Unique Test Data for every Test case. eg every Test has its own User.

Now i have to introduce the Security :-(.... I found your Project, and it looks like a perfect match :-) But one part is missing, when i create a new User, i also have to tell the mock-oauth2-server that this user is allowed to access the app with the following claims.

As fare as i understand it, the "sub" (equal UserId) has to be dynamic in my case. Therefore it would be cool if there were a endpoint where i can update/replace the JSON_CONFIG.

Best regards
G

**Comment by ybelMekk** [comment]
Hello and thanks for the feature request. If understand your issue correctly, i do have a question for you, why do you generate test data each time? It may make your testing "blackboxed" as you dont know what your test input is, and it dosent really sound like a good tests to me. Is it an option to prepare the `JSON_CONFIG` with users you are interessed in and build your integration test cases on that?

**Comment by git9999999** [comment]
Hi ybelMekk

> why do you generate test data each time? It may make your testing "blackboxed" as you dont know what your test input is, and it dosent really sound like good tests to me. 
I run my tests in the maven build and in intellj as junit tests. Locally i run the same test serval times. Now imagine your test create a Message and send it to your System. Your tests validate that the user get just that one message. If you have static data, the second time you run that test there will be two messages in the System. You also need a lot of static test data, if you have 100 Test, you need 100 users :-(.
To have static Test Data is undesirable, every change to that data can have side effects to other tests. If you reuse the eg TestUsers, suddenly the order of the Test influence each other. Even worse, a failed test can influence other tests, this is very hard to detect. I suffered a lot in the past, am sure that dynamic created test data has a lot of advantages. 


> Is it an option to prepare the JSON_CONFIG with users you are interessed in and build your integration test cases on that?
In the maven build, that would be maybe possible, but very unhandy. In local Junit test, this is not possible as i  dot not know the times it get executed and junit is also stateless.

I hope i could answer your questions, if not just let me know.

Best regards
G

**Comment by ybelMekk** [comment]
I see, it makes the test hard to read also. So the feature your after is updating the next response from the IDP?

**Comment by ybelMekk** [comment]
i think we had a similar PR, it this somehow your picture it? https://github.com/navikt/mock-oauth2-server/pull/168/files

**Comment by git9999999** [comment]
> I see, it makes the test hard to read also. So the feature your after is updating the next response from the IDP?

i am not sure if i understand your question right. 
i have not yet implemented the security yet, but i think i will work like this:
1) create the user with a not secured api call in the backend
2) call the IDP and send it the username + roles. 
3) receive the jwt token from the IDP. maybe as response form the 2) or with a separate call
4) call the backend with the jwt token in the header 

i hope this answer your question.

**Comment by git9999999** [comment]
> i think we had a similar PR, it this somehow your picture it? https://github.com/navikt/mock-oauth2-server/pull/168/files Not for jwk tho...

I am sorry, i don't understand the PR and am not familiar with Kotlin :-(

**Comment by ybelMekk** [comment]
Hello. And sorry for delay. I think we talk past  each other here 😊 did you start implementing the security in your application? May be that things become clearer then?

**Comment by git9999999** [comment]
Hi
I was able to solve my Problem without a auth server. See here https://stackoverflow.com/questions/71170940/how-to-use-authorizationserver-in-a-systemtest-to-create-jwt-tokens-without-auth/71377212#71377212

Note that it still would be cool to have that feature. I am able to generate User + TestData for UI Testers to work with. There for, it would be nice to register also the correct user in the auth server with an API. Currently i have to do this by hand. 
It try to make that work with the Spring Authorization Server as i can add there a Rest-Endpoint to register the user.

Best regards
G

**Comment by ybelMekk** [comment]
Oh i see.  Seems like a good solution. Please feel free to open this issue if you don’t find your solution could be solved better with this server. Closing this for now.
