### ISSUE TITLE
multi-segment issuer

### ISSUE THREAD

**Issue by msuret** [navikt/mock-oauth2-server#21]
Hi,
I am trying to use this library to test a code that uses [Keycloak](https://www.keycloak.org/) client.
The problem is that Keycloak issuers are made of 2 URL segments (e.g. `/realms/master`), so the keycloak client will query for tokens at `/realms/master/protocol/openid-connect/token`.
Is it possible to make this work? Thanks!

**Comment by tommytroen** [comment]
@msuret Does the KeyCloak client support a "discovery/well-known" url to configure itself? If so the structure of the issuer url shouldn't be a problem as it get configured by whatever returned from the well-known endpoint. 

Can you provide any more details on the client you are using so we can investigate further?

**Comment by msuret** [comment]
@tommytroen I am using the [official keycloak client](https://www.keycloak.org/docs-api/11.0/javadocs/index.html). It seems that it doesn't configure itself from a well known endpoint but uses predefined paths: https://github.com/keycloak/keycloak/blob/66dfa32cd569a7416de21b4dc04db212e8fccce5/integration/admin-client/src/main/java/org/keycloak/admin/client/token/TokenService.java#L38

**Comment by tommytroen** [comment]
@msuret sorry for the delay on this. We have added support for multisegment issuer in #31. will prob ship a new release sometime next week.
