### ISSUE TITLE
scope issue in standalone server with spring boot application

### ISSUE THREAD

**Issue by rafonsecad** [navikt/mock-oauth2-server#220]
Hi everyone,

I'm trying to set up mock oauth2 as standalone server to test a spring boot application as resource server, however, the application doesn't recognize any of the scopes I set on mock oauth2. This is how I currently configure the user

![image](https://user-images.githubusercontent.com/17520030/159962044-0ec9c401-49c7-430f-b864-63d7e4599f96.png)

As can be seen this user has the scopes `openid`, `profile`, `email`, and `read:teams`.  The application has the following configuration

```yml
spring:
  security:
      oauth2:
        resourceserver:
          jwt:
            #issuer-uri: http://localhost:8090/default/jwks
            jwk-set-uri: http://localhost:8090/default/jwks
```
```java
http.cors()
                .and()
                .csrf()
                .and()
                .authorizeRequests()
                .antMatchers("/team").hasAnyAuthority("SCOPE_read:teams") // .hasAnyAuthority("read:teams")
                .anyRequest()
                .authenticated()
                .and()
                .oauth2ResourceServer()
                .jwt();
        http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
```

The response I'm getting from the application when sending a request to GET /team is

```
HTTP/1.1 403 
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
WWW-Authenticate: Bearer error="insufficient_scope", error_description="The request requires higher privileges than provided by the access token.", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Length: 0
Date: Thu, 24 Mar 2022 16:25:09 GMT
Keep-Alive: timeout=60
Connection: keep-alive
```
The error from the app is

```
2022-03-24 16:29:57.964 DEBUG [app,,,] 26556 --- [nio-8080-exec-1] o.s.s.w.u.matcher.AntPathRequestMatcher  : Checking match of request : '/team'; against '/team'
2022-03-24 16:29:57.964 DEBUG [app,,,] 26556 --- [nio-8080-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Secure object: FilterInvocation: URL: /team; Attributes: [hasAnyAuthority('read:teams')]
2022-03-24 16:29:57.964 DEBUG [app,,,] 26556 --- [nio-8080-exec-1] o.s.s.w.a.i.FilterSecurityInterceptor    : Previously Authenticated: org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken@ffff6aba: Principal: org.springframework.security.oauth2.jwt.Jwt@f310fa13; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@957e: RemoteIpAddress: 127.0.0.1; SessionId: null; Not granted any authorities
2022-03-24 16:29:57.968 DEBUG [app,,,] 26556 --- [nio-8080-exec-1] o.s.s.access.vote.AffirmativeBased       : Voter: org.springframework.security.web.access.expression.WebExpressionVoter@469e4961, returned: -1
2022-03-24 16:29:57.968 DEBUG [app,,,] 26556 --- [nio-8080-exec-1] o.s.s.w.a.ExceptionTranslationFilter     : Access is denied (user is not anonymous); delegating to AccessDeniedHandler

org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.vote.AffirmativeBased.decide(AffirmativeBased.java:84)
```

In the other hand, if I don't set any require scope at the spring security configuration, the token works as expected. I know this is probably a mistake I'm making with the mock server and also don't know much about this kind of authorization so thanks in advance for any help or comment.

**Comment by tommytroen** [comment]
Hi, are you using the MockOAuth2Server from a unit test or do you start it separately (e.g. docker) from the spring app?

Depending on how you use the server you can configure the server to return specific claims in the token (e.g. scope).

**Comment by rafonsecad** [comment]
> Hi, are you using the MockOAuth2Server from a unit test or do you start it separately (e.g. docker) from the spring app?
> 
> Depending on how you use the server you can configure the server to return specific claims in the token (e.g. scope).

Hey, I'm running a standalone server from source on intellij. What I'm doing to configure the scopes is going to debugger page at http://localhost:8090/default/debugger and write the scopes I want

![image](https://user-images.githubusercontent.com/17520030/160155674-9ae4e6ab-eec0-415c-9627-ab650dae3d93.png)

Then I click on Get a token and it redirects to this page

![image](https://user-images.githubusercontent.com/17520030/160156148-48e0b2cf-6146-47de-b494-35eb82f9241b.png)
 
I only type an username (me) and leave the optional claim box empty, After I click on Sign-In I get the token

![image](https://user-images.githubusercontent.com/17520030/160156755-80a375cc-9527-4d28-a7ce-909c105bff52.png)

Here I can see the scopes I want, however the spring app complains the token doesn't have the scope `read:teams`. Looking at the access token on jwt.io debugger, the payload shows

![image](https://user-images.githubusercontent.com/17520030/160158034-4796b50a-e523-4639-8114-7fa0199c7866.png)

Thanks in advance!!

**Comment by tommytroen** [comment]
@rafonsecad Have you tried putting 
```json
{
  "scope": "read:teams"
}
```
into the optional claims box at sign-in?

This should give you a token containing the scope claim.

**Comment by rafonsecad** [comment]
> @rafonsecad Have you tried putting
> 
> ```json
> {
>   "scope": "read:teams"
> }
> ```
> 
> into the optional claims box at sign-in?
> 
> This should give you a token containing the scope claim.

That made the trick, thank you so much!!!

**Comment by brandonsilver** [comment]
I'm in a similar situation with the standalone server. I need to get a token via a client credentials POST with a particular set of scopes. When I perform the request, the scopes get placed into the 'aud' claim instead of the 'scope' claim.

Is there a way to get scopes placed into the 'scope' claim?
