### ISSUE TITLE
Support Resource Owner Password Credentials grant type

### ISSUE THREAD

**Issue by mkutz** [navikt/mock-oauth2-server#226]
For my use case I need to implement a [Resource Owner Password Credentials](https://datatracker.ietf.org/doc/html/rfc6749#section-1.3.3) flow (grant type `password`).

**Comment by mkutz** [comment]
Looks exactly like what I was looking for, yes 😄
Sorry, didn't check open PRs. Feel free to close this.

**Comment by ybelMekk** [comment]
No, i leave it here, makes it more obvious. Thanks for opening the issue anyway 👍🏾

**Comment by ybelMekk** [comment]
Released: https://github.com/navikt/mock-oauth2-server/pull/233
