### ISSUE TITLE
Access OAuth request body

### ISSUE THREAD

**Issue by jonathannaguin** [navikt/mock-oauth2-server#23]
Hello,

I am trying to access the request body but it is always empty.
I believe the OAuth2 server consumes the requesty body when doing its internal handling so when I retrive it using`takeRequest`, I get an empty buffer.

Is there another way to access it?

Thanks!

**Comment by tommytroen** [comment]
@jonathannaguin You are right, this is a bug, the body buffer is read when converting to an internal representation of the request. I dont think you can retrieve it any other way, so I'll put in a fix for this and release a new version.

**Comment by tommytroen** [comment]
@jonathannaguin There is a new release `0.2.3` in maven central that should fix this issue. Please let ut know if you have any issues.

**Comment by jonathannaguin** [comment]
Thanks! It works now 👍
