### ISSUE TITLE
Add alg parameter to initial keys

### ISSUE THREAD

**Issue by loosebazooka** [navikt/mock-oauth2-server#247]
Some clients (google-oauth-client) seem to expect the `alg` parameter when parsing jwks key endpoints (even though they are optional). Can we add those to the initial keys resources to expand compatibility?

**Comment by loosebazooka** [comment]
For instance the jwks endpoint would return something like
```diff
 {
   "keys" : [ {
     "kty" : "RSA",
     "e" : "AQAB",
     "use" : "sig",
     "kid" : "test-default",
+    "alg" : "RSA256",
     "n" : "onZcB1ryWS1keTIcbgsLKJ1UBwL1Wbzse5P2HjkrNwbG3Jy2lefUEcTVJxN8bpLeW460Luz3ScZd3d9p8IoHjmhZ2cyO49E41aBRIlBRzWNpebK5xeC95rSKenYHpOPlLzPgybg2qxallzQUOcKCheiF0fsErlapaA9YmKwzP3DwvzYW4JqSrHhDGWPwUCcsR4dpetwKXP_9tRFso06ryr4um3qiq7giyZEyZVG3fHMplD-5e-2-RrzBiGFW_zvs-XVRGPIf9Y5YNjeQJRuS4vF82V8mNZxEZddtUY5plSz-vgX3GSvANLDH-LZJ76Zmx3a8dEZbI7VxgsBQAqcUlQ"
   } ]
 }
```

**Comment by ybelMekk** [comment]
Hello @loosebazooka and thanks for opening this issue.

This can be added fairly simple.

If your keen open a PR with the suggested change and I will merge it or I can ad it.

cheers

Youssef

**Comment by ybelMekk** [comment]
@loosebazooka could you try this out? https://github.com/navikt/mock-oauth2-server/pull/248
