### ISSUE TITLE
[bug] requestMappings in JSON_CONFIG not working as documented for docker

### ISSUE THREAD

**Issue by patcon** [navikt/mock-oauth2-server#251]
First off, thanks so much for this project! I'm super-stoked to get it working, and to be able to strip a lot of custom work-arounds from a local dev environment ❤️ 

The thing I'm hitting is that I'm unable to use the standalone mode as described, specifically with `requestMappings`. I've confirmed that:
- the config json is being read,
- top-level config can be changed (e.g., `interactiveLogin`),
- malformed `tokenCallbacks` entries cause the server not to start

BUT using the exact config json [as described in the README](https://github.com/navikt/mock-oauth2-server#:~:text=class%20using%20JSON.-,Example,-%3A) does not seem to match and generate any sort of custom token response when hitting the appropriate issuer.

I've created a full reproduction here: https://github.com/patcon/mock-oauth2-repro

Any advice is appreciated! 🙌

**Comment by patcon** [comment]
Yay! Thanks to this comment, I was able to find a work-around by just passing the same JSON into an envvar. I suspect there's something that still needs to be fixed, but I'm glad to not feel crazy anymore...!

**Comment by tronghn** [comment]
Are you sure the config file is being read? Your reproduction setup seems to work fine on my machine by either:
- renaming the file from `./conf/conf.json` to `./conf/config.json`, or 
- pointing the config variable to the correct path (e.g. `JSON_CONFIG_PATH: /app/conf/conf.json`).

**Comment by ybelMekk** [comment]
@patcon tried your bug report, got same result as @tronghn, by updating the config.json file name or update docker-compose.yml, but i dont understand why you use version `0.3.6`? latest [release](https://github.com/navikt/mock-oauth2-server/releases/tag/0.4.7). Seems like their is a default output you get with the miss configuration.

**Comment by patcon** [comment]
Hm. I must have been seeing something else in my actual non-reproduction version, but glad to know...

If I were to think what may have tipped me off: I was reading output logs, and maybe a warning clarifying that file was detected as set in envvar, but not found at the location? But that's very minor..!

Thanks very much both, and apologies for the noise 🙏

**Comment by ybelMekk** [comment]
no need to apologies! thanks for bringing it up and engaging in the project 👍🏾

**Comment by ivebeenlinuxed** [comment]
Hi All! I have the same problem here. I can confirm the three issues above (top level config read, error if file is not available, malformed `tokenCallbacks` cause error.

docker-compose.yaml
```
version: "3.8"
services:
  oauth-mock:
    image: ghcr.io/navikt/mock-oauth2-server:0.5.7
    ports:
      - 8080:8080
    hostname: mock-oauth.localhost
    environment:
      - JSON_CONFIG_PATH=/config.json
      - LOG_LEVEL=VERBOSE
    volumes:
      - ./oauth_mock.json:/config.json
```

config.json
```
{
    "interactiveLogin": false,
    "httpServer": "NettyWrapper",
    "tokenCallbacks": [
        {
            "issuerId": "default",
            "requestMappings": [
                {
                    "requestParam": "scope",
                    "match": "*",
                    "claims": {
                        "sub": "testuser",
                        "aud": [
                            "testaudience"
                        ]
                    }
                }
            ]
        }
    ]
}
```

**Comment by ivebeenlinuxed** [comment]
Can confirm that putting the same config inline using (in powershell) `Get-Content -Raw .\oauth_mock.json | ConvertFrom-Json | ConvertTo-Json -Compress -Depth 5` is a workaround.
