### ISSUE TITLE
Support mocked introspect endpoint

### ISSUE THREAD

**Issue by patcon** [navikt/mock-oauth2-server#252]
Seems like it simply returns:

```json
{
  "active": true
}
```

Thanks for considering!

Alt implementation:
https://github.com/axa-group/oauth2-mock-server/blob/2039693d4fb52949b306e257b52d065667970f66/src/lib/oauth2-service.ts#L411-L416

**Comment by ybelMekk** [comment]
Hello again, same her: https://datatracker.ietf.org/doc/html/rfc7662

some code need to be added, feel free to submit a PR 😄

**Comment by ybelMekk** [comment]
That’s how we work 🤓
