### ISSUE TITLE
feat: add support for x5c chain cert key in /jwks

### ISSUE THREAD

**Issue by patcon** [navikt/mock-oauth2-server#253]
Any advice on how this might be done? Especially curious to figure it out for the standalone server, but maybe I can figure out.

Wondering whether any of the SSL functionality could be leveraged here. Any guidance is appreciated!

https://curity.io/resources/learn/self-contained-jwts/#x5c

**Comment by ybelMekk** [comment]
Hello @patcon and thanks for opening the issue.

We need to add some code to get that bit to work 👍🏾

**Comment by ybelMekk** [comment]
@patcon try out: https://github.com/navikt/mock-oauth2-server/pull/255

not complete, but please try it out in you use-case.

**Comment by patcon** [comment]
Oh heck, I fully expected to need to dive into this myself, and so I'm really humbled by this spike. Thank you so much, Youssef! 🙏 

I'd actually had some back-and-forth later in the week with an employee at our government identity provider, and they seemed to indicate that x5c was redundant to "n" and "e" together: https://github.com/GCTC-NTGC/gc-digital-talent/issues/2716

In your understanding, does this sound correct?

**Comment by ybelMekk** [comment]
Yes, 

the modulus ( n) and exponent ( e) which together are sufficient to construct the RSA Public Key. This key can be then used to validate the signature.

**Comment by patcon** [comment]
Thanks for that :) Since we have control of the code doing the validating, I think I'm just going to advocate we ditch our use of x5c in the client, and build the public key in PEM format ourselves.

So while I feel very grateful, pls don't add more code on my account (that you'll need to maintain).

Of course, if you'd like me to test this even if we won't be using it, I'd be very happy to reciprocate! Would testing it in an x5c-utilizing commit of our codebase be appreciated?

**Comment by ybelMekk** [comment]
Closing this for now.
