### ISSUE TITLE
question: How to set the logging severity for the stand-alone server

### ISSUE THREAD

**Issue by jp7677** [navikt/mock-oauth2-server#272]
Hi there,

When running mock-oauth2-server as a docker container, its logging is very verbose, the debug logging shows a lot of lines like  

```
mock-oauth2-server_1  | 2022-06-08 13:31:01 [nioEventLoopGroup-3-23] DEBUG no.nav.security.mock.oauth2.http.CorsInterceptor - intercept response if request origin header is set: null
```

Is there a way to set the logging severity from the outside using an environment variable so that it can be applied to the stand alone docker image? I tried several of the "standard" ways like setting `_JAVA_OPTIONS=-Dlogging.level.root=WARN` or `JAVA_OPTS -Dlogging.level.root=WARN`, but none of those showed effect.

**Comment by ybelMekk** [comment]
could work? @jp7677 https://github.com/navikt/mock-oauth2-server/pull/276

**Comment by jp7677** [comment]
Hi @ybelMekk, thanks a lot for responding and for creating this PR. The PR works perfectly and completely resolve my question!
