### ISSUE TITLE
Propose to make the library java 8 compliant

### ISSUE THREAD

**Issue by patped** [navikt/mock-oauth2-server#29]
Making the library java 8 compliant will (possibly) make it easier for older applications to migrate from another security-framework.

This means that you loose the ability to use newer java features but this doesn't mean much at this point in time, as you can see in the proposed patch (ref:1). The patch is considered work in progress, but it should give an indication of how small this change really is.

It may be something I'm not aware of or haven't considered, but I'm willing to "do the heavy lifting" if the propose gets accepted.

Ref.
1: https://github.com/patped/mock-oauth2-server/commit/8dfa35c54a60346bc44ae176587d9fb7bd02733c

**Comment by tommytroen** [comment]
initial need not longer there. revisit if necessary.
