### ISSUE TITLE
Support multiple constructors for DefaultOAuth2TokenCallback when using Java

### ISSUE THREAD

**Issue by tommytroen** [navikt/mock-oauth2-server#3]
* Add more constructors according to default values set in DefaultOAuth2TokenCallback

**Comment by shartte** [comment]
Could this be done by adding the `@JvmOverloads` annotation to the corresponding constructor?

**Comment by ybelMekk** [comment]
@tommytroen  any thoughts ☝🏾

**Comment by tommytroen** [comment]
fixed
