### ISSUE TITLE
status check to know when it has successfully started

### ISSUE THREAD

**Issue by ivanskodje** [navikt/mock-oauth2-server#306]
I am looking to run this via docker-compose, and would like to add a status check so we can execute another script when this have successfully been loaded. So mock-oauth2-server have a status script, or api we can curl? 

(Alternative approaches also appreciated).

On Ubuntu we had problems setting up host.docker.internal in hosts file, and made a script to automate it, and would like to do that via our own command so that if the user is on Ubuntu it will automatically update the hosts file.

**Comment by ybelMekk** [comment]
Thanks for opening this issue @ivanskodje !

For the standalone server there is a api endpoint `/isalive` to curl, have you tried this out?

**Comment by ybelMekk** [comment]
It is probably not documented..

**Comment by jksolbakken** [comment]
Added a note in the readme about what @ybelMekk said, closing the issue.
