### ISSUE TITLE
Issue when used with Spring Boot log4j2 starter

### ISSUE THREAD

**Issue by catchin** [navikt/mock-oauth2-server#33]
When using this project together with `org.springframework.boot:spring-boot-starter-log4j2` on Spring Boot 2.4.3, an exception is thrown during startup:
```
java.lang.ExceptionInInitializerError
	[...]
Caused by: org.apache.logging.log4j.LoggingException: log4j-slf4j-impl cannot be present with log4j-to-slf4j
	at org.apache.logging.slf4j.Log4jLoggerFactory.validateContext(Log4jLoggerFactory.java:49)
	at org.apache.logging.slf4j.Log4jLoggerFactory.newLogger(Log4jLoggerFactory.java:39)
```
I created a test project [here](https://github.com/catchin/mock-oauth-server-with-spring-boot)

Probably it would be good to not include logback, but perhaps only rely on slf4j?

**Comment by catchin** [comment]
A workaround is to exclude logback in the gradle configuration:
```
    testImplementation("no.nav.security:mock-oauth2-server:0.3.1") {
        exclude(group = "ch.qos.logback", module = "logback-classic")
    }
````
It would be nicer however if it works without this workaround

**Comment by tommytroen** [comment]
@catchin we will take a look at this. we need a slf4j implementation for the standalone/docker mode, hopefully some gradle gymnastics could do the trick

**Comment by ybelMekk** [comment]
I started on a PR. But after a discussion with my team mates, we see this issue as solved. Du to the fact that that the logback-classic is needed for docker mode run and if used as library an exclude could be a simple workaround. This could be solved if implemented with separate dep. for gradle and docker, but not really worth it.
