### ISSUE TITLE
No longer compatible with java11?

### ISSUE THREAD

**Issue by loosebazooka** [navikt/mock-oauth2-server#356]
When moving from 0.5.1 -> 0.5.5 in gradle it looks like java11 compatibility was lost? Is this intentional? See the "org.gradle.jvm.version" attributes in modules files:

https://repo1.maven.org/maven2/no/nav/security/mock-oauth2-server/0.5.3/mock-oauth2-server-0.5.3.module
https://repo1.maven.org/maven2/no/nav/security/mock-oauth2-server/0.5.1/mock-oauth2-server-0.5.1.module

Forces me to run all my tests in Java17. I need to run them in 11 and 17.

**Comment by loosebazooka** [comment]
I think if you're not using Java17 features, it shouldn't matter if you're keep both values at `VERSION_11`. But I guess this is your call as the maintainer.

Setting `targetCompatibility = JavaVersion.VERSION_17` will not allow the library to be used with java11 projects. As, from what I understand, class files are generated to be only compatible with java17+.

`sourceCompatibility` seems to be a build time check, that metadata is not propagated to the class files. (I'm not sure why anyone would set these different -- maybe some version cross compiling business?)

**Comment by ybelMekk** [comment]
I figure it's reasonable and right to keep the backward compatibility, as the tool is used for older (not as fast running, not looking back dude thinking me 🙈)

could call inn som people with a little better understanding about around the problem here:
📲 -> @tommytroen , @jksolbakken

**Comment by jksolbakken** [comment]
I don't see any issues with going back to 11, at least until the official support ends (in september 2023 iirc).

**Comment by tommytroen** [comment]
@ybelMekk Lets go back to 11

**Comment by loosebazooka** [comment]
thanks for the quick release!

**Comment by ybelMekk** [comment]
> thanks for the quick release!

This is on me. Thanks for reporting 🥇
