### ISSUE TITLE
Management API support

### ISSUE THREAD

**Issue by sazzer** [navikt/mock-oauth2-server#359]
This looks immensely useful for the testing of my code against a "real" Auth0 service. However, if I'm right it only supports the authentication endpoints and not the management API? It would be incredibly useful if there was some way for this to also support the management API endpoints - at the very least the ones for working with users.

Cheers

**Comment by ybelMekk** [comment]
Hi @sazzer and thanks for submitting this issue, just to clarify for me personally, when your talking about management API, what part of the [oauth2 spec](https://oauth.net/2/)are you referring too?

**Comment by sazzer** [comment]
Please ignore me. I apparently wasn't fully awake this morning when I
posted this! I was looking for a mock *Auth0* server and misread the name
of this project. Sorry for the confusion!

**Comment by ybelMekk** [comment]
No problem 😉 Closing this.
