### ISSUE TITLE
Support more negative testing

### ISSUE THREAD

**Issue by mkutz** [navikt/mock-oauth2-server#376]
I'm currently writing some authentication code in my own framework.
The mock-oauth2-server served me really well to get the implementation to work, but now I'm trying to verify some error handling. E.g.:

* The OAuth2 server doesn't accept my login data, or
* the OAuth2 server is not reachable.

I also have some token caching code, I'd like to test. For that I'd like to check if the OAuth2 server was called only once, not twice.

Maybe this is already possible and I just couldn't figure out how to achieve it.
Exposing the internally used `MockWebServer` would probably fulfill my needs already.

**Comment by ybelMekk** [comment]
Hi @mkutz could you provide some examples of negativ testing you´re trying out?

**Comment by daleif** [comment]
I also think it could be a good idea to say have a special `issuerID` that then can respond with things that are predictably wrong. I was wondering if one in that case could use `state` to specify what should go wrong.

**Comment by ybelMekk** [comment]
If your using the mock-ouath2-server in integration tests the `MockWebServer` is exposed: https://github.com/navikt/mock-oauth2-server/blob/2b0f62321a1922610f77ebc5f9c950568f3a7a66/src/main/kotlin/no/nav/security/mock/oauth2/OAuth2Config.kt#L31

**Comment by daleif** [comment]
> If your using the mock-ouath2-server in integration tests the `MockWebServer` is exposed:
> 
> https://github.com/navikt/mock-oauth2-server/blob/2b0f62321a1922610f77ebc5f9c950568f3a7a66/src/main/kotlin/no/nav/security/mock/oauth2/OAuth2Config.kt#L31

In my case I'm using it via docker, so not sure if it is available. I'm just using it to test a plugin for a frameworks from localhost.

**Comment by ybelMekk** [comment]
@daleif, if not used in unit/ integration test, today the config.json only support ssl as a config option: https://github.com/navikt/mock-oauth2-server#unit-tests-1

**Comment by daleif** [comment]
> @daleif, if not used in unit/ integration test, today the config.json only support ssl as a config option: https://github.com/navikt/mock-oauth2-server#unit-tests-1
> 
> Could possible expose more if you know what to config opts you are going to use?

My intention is to use it for testing my code to see of it rejects the id_token if certain criteria is is not as they should be.

I'm not sure if I understand how ssl is related here? In my tests I just treat the mock-oauth2 server as a black box to get OAuth2 / OIDC responses from. My idea would then be to have the server send faulty data back. The spec does mention that the receiving end should always validate the response data.

Thus my suggesting of having a `badissuer` that would return faulty responses depending on the value of the `state` parameter. One could set a bad expire etc.
