### ISSUE TITLE
Any idea why mock-oauth2-server doesn't build locally for me?

### ISSUE THREAD

**Issue by GrahamLea** [navikt/mock-oauth2-server#38]
I cloned the repo, then ran `./gradlew build`, and got:
```
> Task :compileKotlin FAILED
e: .../mock-oauth2-server/src/main/kotlin/no/nav/security/mock/oauth2/debugger/DebuggerRequestHandler.kt: (173, 66): Type mismatch: inferred type is Charset! but String! was expected
```

When I look at the code, that error seems to be right. The line is:
```
private fun String.urlEncode(): String = URLEncoder.encode(this, StandardCharsets.UTF_8)
```
`java.nio.charset.StandardCharsets.UTF_8` is a `Charset`, and `java.net.URLEncoder.encode()` expects a `String`.

**Comment by tronghn** [comment]
`java.net.URLEncoder.encode()` expects a `Charset` as of JDK 10 and upwards. This project is set to use JDK 11, so it sounds like you might have an older version installed and in use.

**Comment by GrahamLea** [comment]
Okay. Thanks. I don't know what's going on but I told jenv to use JDK 11 and Gradle says it's using JDK 11, but when it runs I still get the errors. 🤷🏻‍♂️
