### ISSUE TITLE
Valid authorization tokens rejected in version 0.5.4 and above

### ISSUE THREAD

**Issue by bjerga** [navikt/mock-oauth2-server#380]
I am experiencing what I believe to be a bug when upgrading from version 0.5.3 to 0.5.4. 

I am trying to test a backend app that receives requests from a frontend app. I am using version 2.1.7 of [token-support](https://github.com/navikt/token-support) to set up token validation. The code I am using to mock the authentication looks something like
```kotlin
private val mockOAuth2Server = MockOAuth2Server()

fun mockAuthToken(): String =
    mockOAuth2Server.issueToken(
        issuerId = "mockIssuer", // not the actual value used
        subject = "mockSubject",
        audience = "aud-localhost",
        claims = mapOf(
            "pid" to "mockPid"
        )
    )
        .serialize()
```

When using 0.5.3, my tests are completing as expected. In short, requests are made to a mocked app which either responds 200 OK or 401 Unauthorized, depending on the content of the "Authorization"-header of the request. When using 0.5.4, all requests return 401 Unauthorized.

I'm not entirely sure what causes the bug, but I've been able to pinpoint a piece of code which differs in behaviour when using the different versions. The code that behaves differently can be found [here](https://github.com/navikt/token-support/blob/2.1.7/token-validation-core/src/main/java/no/nav/security/token/support/core/validation/JwtTokenRetriever.java#L43). 

I'll try to explain the issue I'm experiencing based on the code referred to above. Using 0.5.3 of mock-oauth2-server, when using a valid authorization token, `jwtToken.getIssuer()` evaluates to `"http://view-localhost:<port>/<issuer>"`, and `config.issuers`, which the `config.getIssuer(...)` accesses, contains `"<issuer>"` and `"http://view-localhost:<port>/<issuer>"`. Changing to version 0.5.4, and with no other changes, `config.issuers` is different. It now contains `"<issuer>"` (identical) and `"http://localhost:<port>/<issuer>"` (missing the "view-"-part). This leads the filter-predicate to evaluate to false, and the JWT to be considered invalid and the request to be unauthorized.

That's pretty much what I've been able to figure out so far. I'll be happy to provide any more information if the issue is unclear in any way.

**Comment by ybelMekk** [comment]
This are the changes for version 0.5.4: https://github.com/navikt/mock-oauth2-server/pull/338/files

Could be some her..

**Comment by ybelMekk** [comment]
@bjerga Im just thinking loud here, but are you setting `Host` header explicit when requesting, or can you check. what it is set to during request?

**Comment by bjerga** [comment]
@ybelMekk `Host`-header is not set explicitly and it does not seem to be present during the request.

**Comment by tommytroen** [comment]
@bjerga can you share a link to the failing test? does the well-known data contain urls with `view` or without? The `view-localhost` is a common windows hostname for 127.0.0.1 i believe - does this test fail in CI or locally?

**Comment by joakibj** [comment]
We have the same issue with `token-support:2.1.5` and higher (includes `mock-oauth2-server:0.5.4`).
Looks like the `iss` claim uses an entry in the Windows IP to host mapping `C:\Windows\System32\drivers\etc\hosts` (e.g. `view-localhost`) instead of defaulting to the DNS name `localhost` for `127.0.0.1`

This fails locally on Windows but not on CI (Jenkins)

**Comment by ybelMekk** [comment]
windows 🥇

**Comment by ybelMekk** [comment]
closed: https://github.com/navikt/mock-oauth2-server/pull/586

**Comment by tronghn** [comment]
`token-support:3.1.9` and `mock-oauth2-server:2.0.1` are released now with a fix applied. Give them a try if they're still relevant to you @bjerga and @joakibj.
