### ISSUE TITLE
Docker Imange on hub.docker.com

### ISSUE THREAD

**Issue by git9999999** [navikt/mock-oauth2-server#39]
Hi,

Thanks a lot for mock server, that is exactly what i need :-)

I am working in a corporate environment so the docker images get downloaded to our Artifactory. As you need a login for docker.pkg.github.com, this makes it a but un-handy.... for our Infrastructure-Team. It would be cool the Image would be on hub.docker.com, this is the most common place to store docker Images. 

This i just a wish :-)

Cheers Tom

**Comment by jksolbakken** [comment]
Glad that that you enjoy it! We are in the process of moving our stuff to the shiny new "GitHub Container Registry" (ghcr.io) where you won't need to log in. Will that work for you?

**Comment by git9999999** [comment]
i think on ghcr.io => https://github.com/features/packages we have to still login and pay. https://github.com/features/packages#pricing

**Comment by git9999999** [comment]
we made a mistake. i think the usage is free but you need to login
https://docs.github.com/en/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-packages#about-billing-for-github-packages 

on docker.pkg.github.com no login is needed, that makes it way simpler to use in corporate environment

**Comment by jksolbakken** [comment]
On ghcr you can access public images anonymously, see https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#key-differences-between-github-container-registry-and-the-docker-package-registry. If the login part is what's causing you problems you should be fine once we publish there. It's on our todo list, we'll hopefully find time to do it within the next few weeks.

**Comment by git9999999** [comment]
Thanks for your help. We are looking forward to the ghcr.io migration :-)
