### ISSUE TITLE
Signing key ID in generated tokens is same as issuerId

### ISSUE THREAD

**Issue by tbrandirali** [navikt/mock-oauth2-server#397]
It seems that the OAuth2TokenProvider creates signing keys using the Issuer ID as a Key ID, [here](https://github.com/navikt/mock-oauth2-server/blob/d7c829e4cc89dd9f546323cef3e30630bd1c3202/src/main/kotlin/no/nav/security/mock/oauth2/token/OAuth2TokenProvider.kt#L93). Indeed, the tokens generated (at least, by the unit test API) always have the `kid` header set to the input issuerId. So:
```kotlin
val token = server.issueToken(issuerId = "both_issuer_and_kid").serialize()
```
results in a token header like:
```json
{
  "kid": "both_issuer_and_kid",
  "typ": "JWT",
  "alg": "RS256"
}
```
~~This is confusing, especially since the supplied `issuerId` overrides the original `kid`s from the files, even when providing a custom keys file:~~

Is it possible to supply a custom `kid`, ~~or use the `kid`s from my custom keys file~~, or is this not supported?

EDIT: see update to #396

**Comment by ybelMekk** [comment]
Have you tried to use addClaims(Map<string,any>) ?

**Comment by tbrandirali** [comment]
Hi, yes! I'm referring to the `kid` header. My use case is that I'm trying to test edge cases of my Spring Security OAuth2 configuration, including a mismatched key ID. For this I would need to maintain multiple different keys for the same issuer on the mock server, and then be able to reference them separately.

Right now if I pass in my custom keys I then need to use their `kid` as an issuer for fetching tokens and public keys. Essentially there's a 1-to-1 coupling of keys and issuers.

I'm just wondering whether this is just a (currently) missing feature, or if there are specific reasons why it's implemented this way.

**Comment by ybelMekk** [comment]
Missing feature 👍😊

**Comment by tbrandirali** [comment]
Awesome! Thanks a lot for this, I will test it out as soon as I have time.

**Comment by tommytroen** [comment]
@tbrandirali Will the example in this [comment](https://github.com/navikt/mock-oauth2-server/pull/405#issuecomment-1372679307) solve your use-case?

**Comment by tbrandirali** [comment]
Hi, @tommytroen. I've checked out the example and yes, it seems to be fine for my use case. There is perhaps still a lack of flexibilty in managing multiple keys per issuer (especially when supplying custom keys), which I don't think the PR addressed either. However, I don't currently have such use cases, and I understand not wanting to add complexity where not required. I'm cool with closing this.
