### ISSUE TITLE
Feature request: Consider splitting out the standalone mock-oauth2-server to avoid exposing the logback configuration to users

### ISSUE THREAD

**Issue by frehov** [navikt/mock-oauth2-server#403]
Just a suggestion, but consider splitting out the `StandaloneMockOAuth2Server` along with the logback.xml file to a separate library/runnable.
Currently if there's no logback.xml or logback-test.xml defined in the importing project then logback will pick up the provided implementation which now comes from mock-oauth2-server.
Alternatively consider overriding the `logback.configurationFile` property before starting the standalone server and/or rename the file to something like `logback-standalone.xml`

Additionaly layout + pattern is a deprecated construct in logback, use an encoder instead. https://logback.qos.ch/codes.html#layoutInsteadOfEncoder
```xml
<appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
        <pattern>%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{70} - %msg%n</pattern>
    </encoder>
</appender>
```
the above would be the correct configuration.

The following is output from the logging system showing that the logback.xml is bundled with the library and the warning about the deprecated construct mentioned above.
![image](https://user-images.githubusercontent.com/37329363/210112251-bb0afdf6-622c-4eff-8947-a792308cf694.png)

**Comment by ybelMekk** [comment]
Hi @frehov 

Seems like a good suggestion.

Thank you for opening this issue, please open a PR if you have time.

pease

Y
