### ISSUE TITLE
Standalone server, multiple users and additional claims

### ISSUE THREAD

**Issue by kzlar** [navikt/mock-oauth2-server#404]
Hi,
I recently discovered this project and it was very useful for me, thank you!
I'm wondering if there's a way to return different "email" claims based on the user id provided in the interactive login pane.
I've tried the following but it doesn't seem to work:
```
{
   "requestParam": "sub",
   "match": "2",
   "claims": {
     "sub": "2"
     "email": "2@example.com"
    }
},
{
   "requestParam": "sub",
   "match": "3",
   "claims": {
     "sub": "3"
     "email": "3@example.com"
    }
}
```

Any help would be appreciated!

**Comment by ybelMekk** [comment]
Hello @kzlar 

Thanks for opening this issue.

Could you provide a little more details?

About how your are testing, as a library or container? 
How do you configure the server?
How does your request look like and what are the response?

looking forward to

thanks

**Comment by kzlar** [comment]
Hi @ybelMekk ,

Thank you for your response!

I'm using it as a container. 
I configured the server with the default json file.
Not sure what you mean by how the requests look, but generally I'm setting up my dev environment and trying to make it as close as possible to the way the firebase auth emulator works. Basically when you use the firebase auth emulator to emulate the oauth login flow you can choose between users that you created in advance and log in with a single click. This makes it easy to switch users in your dev environment to verify cross-user functionality works.
My initial thoughts (hence the original question here) was to use "sub" as a user_id (1,2,3, etc.) which worked, but I also needed an email claim (like you get when using firebase/gmail oauth) so I was hoping I could configure it through json to add a claim based on sub (e.g. 1 would  automatically get the 1@exmaple.com claim, 2 would get 2@example.com etc.)

I ended up re-implementing the auth form that comes with the server (GET /authorize) in a way that shows several users from a pre-defined list and when you click one it automatically submits the form with the pre-defined claims. So I'm good for now so feel free to close if you don't think this is something interesting for this project in general :)

**Comment by ybelMekk** [comment]
You could always open a PR 👍🏾
