### ISSUE TITLE
Id token should include `sid` claim to enable frontchannel logout

### ISSUE THREAD

**Issue by jonalu** [navikt/mock-oauth2-server#41]
The [ID-porten doc](https://doc.nais.io/security/auth/idporten/#front-channel-logout) states that logout initiated from other RPs in circle of trust results in frontchannel logout requests to all RPs (`GET` `/oauth2/logout`). To perform logout the receiving RP needs to resolve the  session from the `sid` parameter.

The `sid` should be available as a claim on the id_token.

**Comment by ybelMekk** [comment]
You want this as a default? 

I think  it is possible to configure the response as you like with claims?

From doc:
`If you need specific claims in the resulting `id_token` - e.g. `acr` or a custom claim you can also use the `OAuth2TokenCallback`:`

**Comment by jonalu** [comment]
I guess it makes sense not to mimic id-porten in the default configurations. We'll look into how we can make use of the custom claims functionality you proposed. Thanks!
