### ISSUE TITLE
Questions/Requests for features.

### ISSUE THREAD

**Issue by NeilHardie** [navikt/mock-oauth2-server#417]
Hi,

Just wanted to start by saying thank you for this wonderful project.

I’ve got a couple of questions or requests for features as I’ve not figured out a way to configure the mock server quite the way I want it.

1. In the request for the /token endpoint is there any way to be able to return custom ‘elements’ within the response, much like the way claims can be added with tokenCallbacks, but as a separate element instead?  More specifically an element for ‘client_info’.  I’m looking to use this project for mocking when using the MSAL library and this requires a ‘client_info’ element to be able to work correctly?

2. Is there any way to be able to add in other JWT signing algorithms, I can see how to customise the algorithm used, but not how to add in extra algorithms?  More specifically the HS512 algorithm?

Many thanks for the great project.

**Comment by ybelMekk** [comment]
Hi and thanks for opening this issue.

1. Not really sure what you are referring  to here, could you point me to some documentation?
2. This is possible, check out the dock: https://github.com/navikt/mock-oauth2-server#standalone-server
But for your case, the `HS512`  is not supported, only EC and RSA.

this post explains it pretty good: https://stackoverflow.com/questions/39239051/rs256-vs-hs256-whats-the-difference

**Comment by NeilHardie** [comment]
Hi,

Thanks for the prompt response.

Sorry for not being clearer on the first issue.  We're looking at using MSAL within our application (https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/docs/b2c_required_artifacts_and_claims.md), but wanting to use the Mock service for testing, but as per the MSAL documentation a 'client_info' element is required in the token response which is not being provided.  Is there a way of adding this in or is it something that can be added as a future enhancement?

On the second issue, thanks for the link.  Are there any plans for supporting HS512 in the future?

Many thanks.

**Comment by ybelMekk** [comment]
For you first question, seems like its pretty specific for that b2c service so Im not sure we will implement it.

No plans for HS no. If your able to, supply a PR 😃 .

**Comment by ybelMekk** [comment]
Closing this for now. please feel free to open.

**Comment by heyimMarc** [comment]
> Hi,
> 
> Thanks for the prompt response.
> 
> Sorry for not being clearer on the first issue. We're looking at using MSAL within our application (https://github.com/AzureAD/microsoft-authentication-library-for-android/blob/dev/docs/b2c_required_artifacts_and_claims.md), but wanting to use the Mock service for testing, but as per the MSAL documentation a 'client_info' element is required in the token response which is not being provided. Is there a way of adding this in or is it something that can be added as a future enhancement?
> 
> On the second issue, thanks for the link. Are there any plans for supporting HS512 in the future?
> 
> Many thanks.

Hi @NeilHardie,

I'm having the same issue, we are using msal and would like to mock oauth2 but until I'm still researching for a smart solution for local development and e2e tests. Did you already solved the issue, or do you used another mocking solution?
