### ISSUE TITLE
Question regarding extraction of the Public keys

### ISSUE THREAD

**Issue by sjhajharia** [navikt/mock-oauth2-server#435]
I have an application that uses the MockOAuth2Server. I want to get a list of all the Public Keys associated with this Authorisation Server. The current code in my understanding only provides with the KeyProvider class which has the signingKey() method to fetch the JWK but that requires the kid to be passed to it.
Is there any way I can access all the Keys associated with the same or a way to get a list of all the kid associated so that I can iterate over the same and call the signingKey() method multiple times?

**Comment by ybelMekk** [comment]
Hello. Thanks for opening this issue. 

The keyID is by “default” by default if you don’t specify. 

The server behaves as you configure it, if you configure it with n of keys, the keyID is known to you, so you can use the same when iterating over pub keys with provider.signingKey(keyID)

please take a look at ProviderKeyTest
