### ISSUE TITLE
userinfo_endpoint 

### ISSUE THREAD

**Issue by annaitzhaki** [navikt/mock-oauth2-server#438]
hi, is there a way to add fake data to userinfo_endpoint?
email, name etc.

**Comment by ybelMekk** [comment]
Hi!

have you tried to configure custom claims?

ref: https://github.com/navikt/mock-oauth2-server#json_config

**Comment by gpsmit** [comment]
Sorry to reopen this, we are running into the same issue.
I think the problem is that /userinfo is a simple GET without request parameters, so therefore none of the custom claims are getting matched on the /userinfo call

**Comment by tommytroen** [comment]
> Sorry to reopen this, we are running into the same issue. I think the problem is that /userinfo is a simple GET without request parameters, so therefore none of the custom claims are getting matched on the /userinfo call

@gpsmit If you do a GET to the /userinfo endpoint you will get the claims that are inside the token you use for auth (i.e. the bearer token in the authorization header), so you can use requestmapping to include the claims you want when you obtain that token.

**Comment by gpsmit** [comment]
Any advice?

**Comment by ybelMekk** [comment]
The user_info has no params, som no params is checked. 

When a GET to `user_info` is requested, the mock-server just checks the `Authorization` header for `Bearer `, validates token and returns the claims as a json body.

**Comment by ybelMekk** [comment]
https://openid.net/specs/openid-connect-core-1_0.html#UserInfo

@gpsmit im not so familiar with spring and the ouath2 client, but can you intercept the Bearer token sent to the mock-oauth2-server?

**Comment by gpsmit** [comment]
@ybelMekk sorry was on vacation for two weeks.
Steps to reproduce can be done with mock-oauth2-server:2.0.0 docker and the above config
I would expect the email claim from the above config to be returned from /issuer1/userinfo:
1) Start docker and go to /issuer1/debugger
2) As scopes define openid email
3) Get token
4) Use token to perform call to /issuer1/userinfo with Authorization Bearer header
5) Check json result: does not contain email claim

**Comment by gpsmit** [comment]
Perhaps the above config is not appropriate for user info calls, then I would love to know how one would go about configuring mock values for the user info endpoint.
And, if not possible yet; consider this a feature request.

**Comment by ybelMekk** [comment]
@gpsmit
I'm going away for a couple of days. I'll get back to you once I've had the time to troubleshoot.

**Comment by ybelMekk** [comment]
@gpsmit, after conducting some tests and observations, I'd like to explain the following:

```json
{
    "interactiveLogin": true,
    "httpServer": "NettyWrapper",
    "tokenCallbacks": [
        {
            "issuerId": "issuer1",
            "tokenExpiry": 120,
            "requestMappings": [
                {
                    "requestParam": "scope",
                    "match": "read",
                    "claims": {
                        "email": "email@test.com"
                    }
                }
            ]
        }
    ]
}
```

* The requestParam serves as the key for a specific request-callback that the mocked server searches for within its tokenCallbacks.requestMappings[].

* In your case, the value of the scope key in the /token request should match the "read" value. Alternatively, you could use "requestParam": "grant_type" with "match": "authorization_code" or any "requestParam": "grant_type" with "match": "*".

To demonstrate, consider the following curl command:

```bash
curl -k -v -X POST -H 'Content-type: application/x-www-form-urlencoded' \
-d "client_id=mytestclient&scope=read&grant_type=client_credentials  http://localhost:8080/issuer1/token
```

Executing this command should generate a token containing the custom claim "email": "email@test.com".

Following this, you can make a request to the info_endpoint using:

```bash
curl -H "Authorization: Bearer ey.."  http://localhost:8080/issuer1/userinfo
```

The response should resemble the following JSON:

```json
{
  "sub" : "testuser1",
  "aud" : [ "read" ],
  "nbf" : 1696922793000,
  "azp" : "mytestclient",
  "iss" : "http://localhost:8080/issuer1",
  "exp" : 1696926393000,
  "iat" : 1696922793000,
  "email": "email@test.com"
  "jti" : "645ef42b-771c-4fa9-83cc-07d9e0943ea1",
  "tid" : "issuer1"
}
```

The "match" parameter in requestMappings specifies which requestMappings[] you are interested in as a callback.

I hope this has provided some clarity.

**Comment by gpsmit** [comment]
Thanks for clarifying.
I can indeed make it work if I choose grant_type = authorization_code, so I have a way forward thanks for that.

Still some discussion:  
In the debugger, and per standard, I cannot say scope=read only, as it always needs a openid value in the scope. I cannot get a token without it, so mimimum would be scope=openid+read.   
If I then configure match="openid read" it does match.
It would be nice to be able to partial match on the requestParams, as scope values are almost always multi value.
Now it needs to exactly match the exact string instead of separate values.

**Comment by ybelMekk** [comment]
This can be a nice little feature, I can look into it 👍🏾

**Comment by ybelMekk** [comment]
@gpsmit  seems like @kvokacka answered your 🙏🏾 https://github.com/navikt/mock-oauth2-server/pull/578

**Comment by gpsmit** [comment]
thanks guys, amazing work.
Again thanks for working through this with me, happily applying this project everywhere we need oauth
