### ISSUE TITLE
Make "maxLifetimeSeconds" of token configurable

### ISSUE THREAD

**Issue by RG9** [navikt/mock-oauth2-server#46]
Right now "maxLifetimeSeconds" is hardcoded for 120 seconds in `OAuth2HttpRequest` in call of `requirePrivateKeyJwt`.

Example:
```java
mockOAuth2Server.getConfig().setMaxTokenLifetime(MOCK_AUTH_SERVER_MAX_TOKEN_LIFETIME_SECONDS);
```

Motivation: Testing refreshing token expiry

**Comment by tommytroen** [comment]
@RG9 thanks for your input. This value could certainly be configurable, however I'm not sure that will help your use case with refresh on token expiry (if I understood it right - using the refresh_grant to refresh an access_token)? Let me know if I have misunderstood.

The `requirePrivateKeyJwt` is for validating `client_assertion`s only - i.e. what you use to authenticate your client (meaning the `client_authentication_method` such as e.g. basic auth - `client_secret_basic` or in this case `private_key_jwt`) when requesting a grant. Those JWTs are usually short-lived and in many cases one-time-use only (to prevent from replay etc) and should never be refreshed. 

The mock-oauth2-server supports the refresh grant with any `client_authentication_method` so the lifetime of the `client_assertion` should not be an issue unless you need to test a use case where the authorization server only supports `private_key_jwt` with a specific expiry. If that is the case let me know.

**Comment by RG9** [comment]
You're right, sorry, I misunderstood purpose of this assertion. The actual problem I had was with "clock skew". Thanks for good explanation!
