### ISSUE TITLE
client_id client_secret to test with oauth2 ruby gem

### ISSUE THREAD

**Issue by miteshp22** [navikt/mock-oauth2-server#460]
Hi, 

I am trying to work with the oauth2 ruby gem which requires client_id and client_secret. I am attempting to test with this mock server but was wondering if there was a way to test this way or not.

Reference:
oauth2 gem: https://gitlab.com/oauth-xx/oauth2#customize-authorize_url-and-token_url

**Comment by ybelMekk** [comment]
Hi!

Have you tried?

Do you have any setup to ref to?

**Comment by miteshp22** [comment]
Hi my question has actually shifted now. 

I am using the default configuration.
http://localhost:8080/default/.well-known/openid-configuration

I am not sure what the default configuration actually looks like though. I did not see this in the code base. So I ended up navigating to the debugger: http://localhost:8080/default/debugger

Anyways, I used the following ruby code to authenticate and get userinfo:

```
require 'oauth2'

client = OAuth2::Client.new('debugger', 'someSecret',
                            site: 'http://localhost:8080',
                            authorize_url: '/default/authorize',
                            token_url: '/default/token')

# access = client.auth_code.get_token('code_value', redirect_uri: 'http://localhost:8080/default/debugger/callback')
access = client.client_credentials.get_token
resp = access.get("/default/userinfo")
puts resp.body
```

My issue now is the authentication grant. I can use any authentication grant for example auth_code or client_credentials and it will still return me a WFT and it will still work. Is this just how the mock server is suppose to work?

**Comment by miteshp22** [comment]
Hi,

I see you have thumbed up my comment -- does this confirm my statement where the mock server is suppose to work with any authentication grant and returns a JWT for it?

**Comment by ybelMekk** [comment]
Hello, should be listed her: https://github.com/navikt/mock-oauth2-server#features

What grants the mock-oauth2 supports
