### ISSUE TITLE
Possibility to revoke token

### ISSUE THREAD

**Issue by abhishek-rdm** [navikt/mock-oauth2-server#488]
Is there a possibility to revoke the token using the endpoint

oauth2/revoke.

Based on 
https://datatracker.ietf.org/doc/html/rfc7009#section-2.2

**Comment by ybelMekk** [comment]
@tommytroen ☝🏾

**Comment by tommytroen** [comment]
@abhishek-rdm We do not support the revocation endpoint at the moment, it is however something we could consider adding. Do you need just the endpoint, or do you also need the refresh token to be invalidated? 

If you use the mock server in unit tests, i.e. not the docker image, you can customize the server by adding additional routes and implement the endpoint yourself. Let me know if you want an example.

**Comment by abhishek-rdm** [comment]
@tommytroen thanks for looking into it.
So I am using the mock-auth2 server as a docker container in k8s. 
Our Frontend app calls the oauth2/revoke for invalidation of the token through a signout button.  Adding revoke might help us to test signouts as well.

**Comment by tommytroen** [comment]
@abhishek-rdm I have created a PR for the revocation endpoint here: #504, currently we only support refresh tokens as the access tokens are self contained and can as such not be revoked. Would this suit your needs?

**Comment by abhishek-rdm** [comment]
@tommytroen I think that should do the work.
thanks a lot!!

**Comment by tommytroen** [comment]
@abhishek-rdm I have published a new release - [0.5.10](https://github.com/navikt/mock-oauth2-server/releases/tag/0.5.10) - which contains the revocation endpoint. If you have any issues with it please open a new issue 😄
