### ISSUE TITLE
Testcontainer failes to verify mock-oauth2-server startup

### ISSUE THREAD

**Issue by kokorin** [navikt/mock-oauth2-server#51]
The following code snippet starts a container, but can't check that container listens on internal port.

```java
private static final DockerImageName MOCK_OAUTH_NAME = DockerImageName
        .parse("ghcr.io/navikt/mock-oauth2-server:0.3.4");
@Container
public static GenericContainer mockAuthServer = new GenericContainer(MOCK_OAUTH_NAME)
        .withExposedPorts(8080)
        .waitingFor(Wait.forListeningPort());
```

Probably the issue is related to https://github.com/testcontainers/testcontainers-java/issues/3317

Check demo app which reproduces the problem: [demo.zip](https://github.com/navikt/mock-oauth2-server/files/6806660/demo.zip)

Workaround: use log message Wait:
```java
private static final DockerImageName MOCK_OAUTH_NAME = DockerImageName
        .parse("ghcr.io/navikt/mock-oauth2-server:0.3.4");
@Container
public static GenericContainer mockAuthServer = new GenericContainer(MOCK_OAUTH_NAME)
        .withExposedPorts(8080)
        .waitingFor(Wait.forLogMessage(".*started server.*", 1));
```

**Comment by ybelMekk** [comment]
I dot think it is much here for to do here. The workaround seems legit with a wait for container.
