### ISSUE TITLE
HTTP 405 Method Not Allowed for custom CSS and JavaScript files.

### ISSUE THREAD

**Issue by BennieCopeland** [navikt/mock-oauth2-server#513]
When adding a custom login page, I get an HTTP 405 when attempting to add additional assets like CSS or JavaScript as separate files. I work in an environment where access to the internet may not be available or blocked, so I don't want to use resources from a CDN. Is this possible?

**Comment by ybelMekk** [comment]
@jksolbakken or @tronghn, I have e little knowledge about this, do you have some more info about this feature?

**Comment by tommytroen** [comment]
@ybelMekk I think we might need to introduce a "assets" path flag or something in order to support this, and then serve the files from the directory from a given path.

**Comment by tommytroen** [comment]
@ybelMekk I'll have a quick look to see how much work is needed.
