### ISSUE TITLE
Reject authorization code

### ISSUE THREAD

**Issue by chaptergy** [navikt/mock-oauth2-server#543]
I'm trying to create a test, which verifies the app's behavior, when the authorization code is rejected by the oauth server. However, it seems, that the actual content of the code is irrelevant to the mock server, and a token is always issued. Furthermore there does not seem to be a way to override the response in such a way, that it does not return a valid token, but an error instead. The `enqueueCallback()` method appears to be the only control we have over the return value, but it is only able to generate a token.

It would be great if we would also be able to return an error either for a specific token, or just once.

Thanks!
```[tasklist]
### Tasks
```

**Comment by ybelMekk** [comment]
Improved English: Hello @chaptergy!

Thank you for creating this issue. I can definitely see the use case here. If you have knowledge of Kotlin or Java, please feel free to submit a pull request. Your contribution is warmly welcomed.

Sail smoothly!
