### ISSUE TITLE
No container image for 2.0.1

### ISSUE THREAD

**Issue by BennieCopeland** [navikt/mock-oauth2-server#544]
There is no container image published for the latest 2.0.1. Can you please make this available?

**Comment by ybelMekk** [comment]
Seems like wee need to do some clean up, the job failed and those pushing to sonar and maven are always so fragile, we will check this up!

**Comment by BennieCopeland** [comment]
Thank you!

**Comment by ybelMekk** [comment]
should be fixed now @BennieCopeland

**Comment by programista-zacny** [comment]
Nope... for me still version 1.0.0 is the newest one. Maybe it needs time to build/propagate?
And there is no more 2.0.1? I think I saw it in the latest release info :)

**Comment by ybelMekk** [comment]
should be but it can take time.
ref: https://central.sonatype.com/artifact/no.nav.security/mock-oauth2-server/overview

**Comment by ybelMekk** [comment]
Update at tested in a local project, should be found in repository now, i hope 🌈

**Comment by programista-zacny** [comment]
`docker pull ghcr.io/navikt/mock-oauth2-server:2.0.0` fails 😿

**Comment by ybelMekk** [comment]
checking

**Comment by ybelMekk** [comment]
@programista-zacny could u check now?

**Comment by programista-zacny** [comment]
It's working 🔥 I can pull `2.0.0` image.
I'm also checking here https://github.com/navikt/mock-oauth2-server/pkgs/container/mock-oauth2-server
and new version 2.0.0 is available.

btw. what happened to 2.0.1 version? :)

**Comment by ybelMekk** [comment]
the 2.0.1 was an mistake by me releasing it, like a panic thing 😱,  so I clean up after myself, and hope 🌈  i wont happen again, the release pipeline is a bit fragile, and the biggest issue is publish to maven..
