### ISSUE TITLE
Support for kotlin 1.6.x

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [navikt/mock-oauth2-server#545]
Hello,

I added maven dep below to my project.

```
    <dependency>
      <groupId>no.nav.security</groupId>
      <artifactId>mock-oauth2-server</artifactId>
      <version>1.0.0</version>
      <scope>test</scope>
    </dependency>
```

Then I have this error

```
Kotlin: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
```

I am using openjdk17.0.3 and Kotlin 1.6.21 and cannot upgrade it due to company restriction.

**Comment by xuan-nguyen-swe** [comment]
I tried other Kotlin versions on my private machine:

1.7.21 => doesn't work
1.8.0, 1.8.22 => works

**Comment by ybelMekk** [comment]
Hello @xuan-nguyen-swe , have you tried to use an older version, say, 0.5.10 ? before upgrade of breaking changes?

**Comment by xuan-nguyen-swe** [comment]
@ybelMekk same things happen when using 0.5.10

**Comment by ybelMekk** [comment]
hm, you tried to set compiler options? https://kotlinlang.org/docs/gradle-compiler-options.html#attributes-common-to-jvm-js-and-js-dce

**Comment by xuan-nguyen-swe** [comment]
@ybelMekk I am using maven.

Let me prepare and send you a dummy spring boot application that also has the error.

**Comment by xuan-nguyen-swe** [comment]
I had time to prepare this from my private machine :)

[demo-spring-mock-oauth2.zip](https://github.com/navikt/mock-oauth2-server/files/12593688/demo-spring-mock-oauth2.zip)

```
demo> java --version
openjdk 17.0.2 2022-01-18 LTS
OpenJDK Runtime Environment Corretto-17.0.2.8.1 (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.2.8.1 (build 17.0.2+8-LTS, mixed mode, sharing)

demo> mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)
Java version: 17.0.2, vendor: Amazon.com Inc., runtime: C:\Users\...\.jdks\corretto-17.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

demo> mvn clean verify

...
[INFO] --- kotlin-maven-plugin:1.6.21:test-compile (test-compile) @ demo ---
[INFO] Applied plugin: 'spring'
[ERROR] C:/Users/.../.m2/repository/no/nav/security/mock-oauth2-server/1.0.0/mock-oauth2-server-1.0.0.jar!/META-INF/mock-oauth2-server.kotlin_module: (-1, -1) Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:00 min
[INFO] Finished at: 2023-09-13T07:28:35+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.6.21:test-compile (test-compile) on project demo: Compilation failure
[ERROR] C:/Users/.../.m2/repository/no/nav/security/mock-oauth2-server/1.0.0/mock-oauth2-server-1.0.0.jar!/META-INF/mock-oauth2-server.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
```

**Comment by ybelMekk** [comment]
Hello, haven't had time too check it out, I've give it a new try 😄

**Comment by ybelMekk** [comment]
Seems like your restrictions on kotlin 1.6.21 is not compabaile with kotlin 1.8 + , so the simplest solution for you is to downgrade your mock-oauht2-server to <= 0.5.7.

**Comment by ybelMekk** [comment]
yeah i agree, we haven't planed it, but we can create an issue and see if the demand is needed, could also be a PR if you have time 😄

**Comment by xuan-nguyen-swe** [comment]
> we can create an issue

Why do we need to create another issue if this current one is here already?

**Comment by xuan-nguyen-swe** [comment]
> could also be a PR if you have time

I will see if I could find time to create a PR

**Comment by xuan-dai-nguyen-db** [comment]
Our project is updated to newer Kotlin, so we don't need this support. Let's see if someone still need this then we could reopen this ticket. What do you think?

**Comment by ybelMekk** [comment]
reopen if requested
