### ISSUE TITLE
Basic Client Authentication not supported for the Token Exchange Grant

### ISSUE THREAD

**Issue by valdemon** [navikt/mock-oauth2-server#558]
- As pointed out un the [RFC8693](https://www.rfc-editor.org/rfc/rfc8693.html#name-request) the `Token Exchange Request` can be authenticated:
```
" ... using the normal mechanisms provided by OAuth 2.0. [Section 2.3.1](https://www.rfc-editor.org/rfc/rfc6749#section-2.3.1) of [[RFC6749](https://www.rfc-editor.org/rfc/rfc8693.html#RFC6749)] defines password-based authentication of the client, ..."
```

- When performing the request with the `clientId` & `clientSecret` basic auth I'm getting the error:
```
"request must contain a valid client_assertion."
```
- this is likely because it is assumed that the authentication should be of type `JWT`: [OAuth2HttpRequest.kt#L34](https://github.com/navikt/mock-oauth2-server/blob/cb5e0b63f0527cc5b94ad1fb6ea742622a06c163/src/main/kotlin/no/nav/security/mock/oauth2/http/OAuth2HttpRequest.kt#L34)
- the basic client authentication is present in the request, as debug shows:
<img width="776" alt="image" src="https://github.com/navikt/mock-oauth2-server/assets/5364850/8b43fa6c-d918-4385-ba2b-766bdee493aa">

**Comment by ybelMekk** [comment]
Hello!

Thank you for opening this issue.

If you have the time, a pull request would be greatly appreciated.

Sail slowly.

Youssef

**Comment by valdemon** [comment]
@ybelMekk 
Hi, there you go: https://github.com/navikt/mock-oauth2-server/pull/564
