### ISSUE TITLE
Support changing Clock to control time in testing with embedded server

### ISSUE THREAD

**Issue by xuan-dai-nguyen-db** [navikt/mock-oauth2-server#581]
Currently the library uses system clock to calculate time related fields when issue/validate token.
It would be nice if use-site could set the java.time.Clock instance to control timing behaviours of mock-oauth2-server in tests.

**Comment by kvokacka** [comment]
Hello,
is anybody working on this? 
Can we also add HTTP endpoint to be able to set clock when running mock-oauth2-server as docker container please?

**Comment by ybelMekk** [comment]
Hei, nothing planned.. can have a look :)

**Comment by tommytroen** [comment]
@xuan-dai-nguyen-db you should be able to override the issue time in the token by setting the time in the `OAuth2TokenProvider` in #668, see README for an example. 

@kvokacka #668 lets you configure the system time with JSON config for the docker container.

**Comment by xuan-dai-nguyen-db** [comment]
Amazing! Thanks @tommytroen!

**Comment by xuan-dai-nguyen-db** [comment]
@tommytroen with this change, is it possible to set time after running the embedded server?
For example, I would like to use system clock to start the embedded server when Spring App starts.
Then for test A, I want to issue a token with a fixed time in 01.01.2000.
For test B, I want to issue a token with a fixed time in 01.01.2020.
