### ISSUE TITLE
dynamic clientid for other value than sub

### ISSUE THREAD

**Issue by anasoid** [navikt/mock-oauth2-server#590]
actually the pattern  ${clientId} work only for sub and can be used for other field, it wil be usefull to have dynamic value on other field

**Comment by ybelMekk** [comment]
Hello, and thank you for raising this issue. Could you kindly rephrase the question and offer some examples? This would make it easier to understand your intended meaning.

Youssef

**Comment by anasoid** [comment]
hello,

actually if you add configuration like this 
```
"requestParam": "scope",
"match": "scope1",
"claims": {
    "sub": "${clientId}",
     "appid": "${clientId}",
    "aud": [
        "audByScope"
    ]
}
```

the value of sub will be replaced by clientid but not the value of appid, I expected that all ${clientId} will be replaced.

thanks

**Comment by kvokacka** [comment]
Hi @anasoid 
this should be already possible (for `CLIENT_CREDENTIALS` grant type) with [this ](https://github.com/navikt/mock-oauth2-server/releases/tag/2.1.0) or later release. Have you tried the latest release?

**Comment by ybelMekk** [comment]
See this as fixed, closing
