### ISSUE TITLE
Unique new refresh token on refresh

### ISSUE THREAD

**Issue by petertgiles** [navikt/mock-oauth2-server#638]
Hello and thanks for this tool!  We're using the standalone server in a docker container to test our web application.  I'd like to write a test to confirm that we're properly rotating our refresh tokens.  However, it seems like the server always echos back the same refresh token.  Is it possible to have a unique refresh token generated on refresh?
![image](https://github.com/navikt/mock-oauth2-server/assets/8978655/f0303c00-58d8-4bf1-a084-0873f160c7c5)

**Comment by tommytroen** [comment]
@petertgiles I have created a PR here #645  which should give you what you need
