### ISSUE TITLE
Out of data README

### ISSUE THREAD

**Issue by mm326** [navikt/mock-oauth2-server#643]
Hi since the removal of scope from the request params

` {
                    "requestParam": "scope",
                    "match": "scope1",
                    "claims": {
                        "sub": "subByScope",
                        "aud": [
                            "audByScope"
                        ]
                    }
                }`

is no longer applicable

**Comment by ybelMekk** [comment]
Should be updated, yes!

**Comment by tommytroen** [comment]
The scope param is only removed from the `authorization_code` grant, other grant types such as `client_credentials` still use `scope` in the token request. We can add a short note in the example that it is applicable to other grants than auth code.

**Comment by mm326** [comment]
Thanks!
