### ISSUE TITLE
Question regarding regex replace in requestMappings

### ISSUE THREAD

**Issue by bit-sbonzelet** [navikt/mock-oauth2-server#683]
Hello

Regarding the feature developed in #578.
Should the matching also extend to other fields than `audience`?

I try to get the following configuration to work so that i can request a scope of `testscope:something` and get it attested in the JWT by the system.
But as of now I only get the string `${scope}` attested, not the expected replaced value of `testscope:something`.

my configuration:
```
{ "interactiveLogin": true,
  "httpServer": "NettyWrapper",
  "tokenCallbacks": [
    {
      "issuerId": "mock_issuer",
      "tokenExpiry": 36000,
      "requestMappings": [
        {
          "requestParam": "scope",
          "match": "testscope:.*",
          "claims": {
            "sub": "${clientId}",
            "scope":  "${scope}"
}}]}]}
```
Docker image version: ghcr.io/navikt/mock-oauth2-server:2.1.5

Kind Regards
 Simon

**Comment by tommytroen** [comment]
@bit-sbonzelet #699 should fix the scope issue
