### ISSUE TITLE
`OAuth2TokenProvider` should allow a flexible `systemTime`

### ISSUE THREAD

**Issue by xuanswe** [navikt/mock-oauth2-server#691]
A global fixed `systemTime` is not enough to write tests in practice at all.

I propose to change the current implementation

```
class OAuth2TokenProvider(
        private val keyProvider: KeyProvider = KeyProvider(),
        val systemTime: Instant? = null,
    )
```

to the backward compatible implemenation like below

```
typealias TimeProvider = () -> Instant?

class OAuth2TokenProvider(
  private val keyProvider: KeyProvider = KeyProvider(),
  private val timeProvider: TimeProvider,
) {
  val systemTime
    get() = timeProvider()

  @JvmOverloads
  constructor(
    keyProvider: KeyProvider = KeyProvider(),
    systemTime: Instant? = null,
  ) : this(keyProvider, { systemTime })
}
```

I am not sure if we need to adapt anywhere else (ex. `OAuth2TokenProviderDeserializer`) with this change or not.

**Comment by xuanswe** [comment]
@ybelMekk do you agree so that I can contribute a PR?

**Comment by xuanswe** [comment]
From my understanding, `OAuth2TokenProvider` is created only in 2 places:

* `OAuth2TokenProviderDeserializer`

  Here, the purpose is to convert json string into `OAuth2TokenProvider` object.
  In this case, we only need static `systemTime`, so not relevant to the change.

* `OAuth2Config`

  Here, it could be done programmatically, both static and dynamic `systemTime` are possible.

**Comment by xuanswe** [comment]
Hi, could you please review the PR?

**Comment by ybelMekk** [comment]
Could u please run `:formatKotlin` and then push the changes?
