### ISSUE TITLE
Support interactive login with pre-populated claims

### ISSUE THREAD

**Issue by nealeu** [navikt/mock-oauth2-server#696]
We often want to switch between different users with the same claims (or similar), but currently we have the choice of automatic login, or having to paste in the claims each time for interactive login (because password managers aren't helpful here).

Would you be happy to accept a PR to allow the following config to mean that the claims get populated within login.ftl?

```json
{
    "interactiveLogin": true,
    "httpServer": "NettyWrapper",
    "tokenCallbacks": [
        {
            "issuerId": "issuer1",
            "tokenExpiry": 120,
            "requestMappings": [
                {
                    "requestParam": "scope",
                    "match": "scope1",
                    "claims": {
                        "sub": "subByScope",
                        "aud": ["audByScope"]
                    }
                }
            ]
        }
    ]
}

```
Such that the claims box would be automatically populated with `{
                        "sub": "subByScope",
                        "aud": ["audByScope"]
                    }`.

This would greatly help our exploratory testing, as in the 90% case the user will just be hitting the login button, but the other 10% they may change the username or claims.

**Comment by jp7677** [comment]
Look for `loginPagePath` in https://github.com/navikt/mock-oauth2-server?tab=readme-ov-file#json_config
Within your own login page, all possibilities are open for e.g. adding buttons that prefill claims.

**Comment by nealeu** [comment]
Thanks. That did the trick.
