### ISSUE TITLE
support OIDC single/global/central logout endpoint 

### ISSUE THREAD

**Issue by tommytroen** [navikt/mock-oauth2-server#7]
Ref:
* OpenID Connect Session Management v1.0 Spec
* OpenID Connect Front-Channel Logout v1.0 Spec
* OpenID Connect Back-Channel Logout v1.0 Spec

Should be simple as this is afterall a mock, however it should validate that the correct params are received at the endsession endpoint and do proper redirects as per spec

**Comment by tronghn** [comment]
Note: RP-initiated logout has been split out to [its own specification](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) as per [#1085 Make RP-Initiated Logout description self-contained](https://bitbucket.org/openid/connect/issues/1085/make-rp-initiated-logout-description-self).
