### ISSUE TITLE
Validation of tokens doesn't consider OAuth2Config.tokenProvider.systemTime

### ISSUE THREAD

**Issue by xuanswe** [navikt/mock-oauth2-server#700]
## How to reproduce the bug

1. Set the systemTime to a constant value to some years in the past
   ```
   MockOAuth2Server(
     OAuth2Config(
       tokenProvider = OAuth2TokenProvider(
         systemTime = Instant.parse("2020-10-10T00:00:00Z") // now is 2024
       )
     )
   )
   ```
2. Issue a token with 1 hour expiration
3. Validate the token
    * Expectation: token is valid
    * Actual: token is expired

## Additional Information

I found `Instant.now()`, which is still used at 2 places.
I think it should be replaced by the value of getter `OAuth2Config.tokenProvider.systemTime`.

![image](https://github.com/navikt/mock-oauth2-server/assets/24372782/760e3ef5-3646-46f4-a7fa-ef1b8a538eaf)

**Comment by xuanswe** [comment]
@ybelMekk could you have a look?
I am not sure how to inject the config to these places and where/how to write tests for this case.
If you could give me some guidance, I could implement and create PR.

**Comment by xuanswe** [comment]
I tried to change like this:

```
fun SignedJWT.expiresIn(systemTime: Instant? = null): Int =
    Duration.between(systemTime ?: Instant.now(), this.jwtClaimsSet.expirationTime.toInstant()).seconds.toInt()
```

And provide the systemTime for all implementation of `GrantHandler`. These places look fine, I think.
![image](https://github.com/navikt/mock-oauth2-server/assets/24372782/4143bdc5-67a8-4fa4-9f76-80e9b5f7741c)

Most of them are fine with a direct parameter passing.
But there is one long call chain below, that I don't feel good about it.
`TokenExchangeGrantHandler.tokenResponse()`
=> `OAuth2HttpRequest.asTokenExchangeRequest(systemTime: Instant? = null)`
=> `OAuth2HttpRequest.ClientAuthentication.requirePrivateKeyJwt(..., systemTime: Instant? = null)`
=> `clientAssertion.expiresIn(systemTime)`

I didn't try to do the same for the method `toX509Certificate` in `SslKeystore`, as I think it would be a mess if doing like that.

IMO, we should somehow have a way to allow access the `OAuth2Config` object directly, then we can avoid passing values everywhere. What do you think?

**Comment by xuanswe** [comment]
Yes, I like your idea, which is better than mine. The value should be derived from this.jwtClaimsSet itself. Nice!

**Comment by xuanswe** [comment]
How about `SslKeystore`?

**Comment by xuanswe** [comment]
Oh, wait. I don't think we can use `this.jwtClaimsSet.issueTime.toInstant()` in `expiresIn`. I understand that this must be the remain time from systemTime value.

**Comment by ybelMekk** [comment]
its should be the same at the systemTime, at the creation time in claimset?

**Comment by xuanswe** [comment]
https://datatracker.ietf.org/doc/html/rfc6749#section-5.1
> expires_in
         RECOMMENDED.  The lifetime in seconds of the access token.  For
         example, the value "3600" denotes that the access token will
         expire in one hour from the time the response was generated.
         If omitted, the authorization server SHOULD provide the
         expiration time via other means or document the default value.


"from the time the response was generated" not "from the time the token was generated"

**Comment by tommytroen** [comment]
I think you are talking past each other 😄 

`expiresIn` should not be used for token validation, it is part of the token response and not the token itself. as a sidenote it can be manipulated so should never be used for validation, its main most common purpose is for caching etc. 

In your example the expectation is wrong: a token with 1 hour expiration will only be valid for 1 hour after it is issued, i.e. in 2020. So unless your validation code has changed its clock to the same as `systemTime`  your token will always be expired. To get it to validate without changing the clock you have to give it an expiration of 4 years plus the time.

**Comment by xuanswe** [comment]
> `expiresIn` should not be used for token validation, it is part of the token response and not the token itself. as a sidenote it can be manipulated so should never be used for validation, its most common purpose is for caching etc.

Thanks for your confirmation @tommytroen!

> To get it to validate without changing the clock you have to give it an expiration of 4 years plus the time.

But what I want is to validate "with changing the clock."
I want to set the entire environment to a clock that I can control (without touching the real system clock, of course).
This will make sure my test will always run correctly without caring about the current time of the OS clock.
The whole mock server, including validation, should certainly use the value of OAuth2Config.tokenProvider.systemTime and not using the OS clock.

**Comment by xuanswe** [comment]
> `expiresIn` should not be used for token validation, it is part of the token response and not the token itself. as a sidenote it can be manipulated so should never be used for validation, its most common purpose is for caching etc.

Thanks for your confirmation, @tommytroen!

> So unless your validation code has changed its clock to the same as systemTime your token will always be expired.

Oh, do you mean that the mock server doesn't validate the expiration of the token, but the logic of the application does?

**Comment by ybelMekk** [comment]
@xuanswe, hope u had a good summer,  is this still an issue?

**Comment by xuanswe** [comment]
Thanks @ybelMekk! Hope you enjoy your summer as well :).

Yes, I am still waiting for your opinion on how to continue.

Maybe we can just pass the configured systemTime everywhere for now if it works.
About the optimization to avoid variable passing, we could be in a separate ticket because it requires some research and blocking the actual issue?

What do you think? If you agree with this approach, I guess I can find time to work on it soon.

**Comment by tommytroen** [comment]
@xuanswe Sorry for the late reply, has been a long summer 😄 
You are correct that the introspection and userinfo endpoints did not use the systemTime when validating tokens. The other endpoints should use the tokens as is, .i.e. not validating. I have created a PR which should solve your issue: #730

**Comment by xuanswe** [comment]
> Sorry for the late reply, has been a long summer 😄

@tommytroen Hope you enjoyed your vacation :-)



> I have created a PR which should solve your issue: #730

Amazing! I will try again and see if it can fix my test case. Thank you a lot!
