### ISSUE TITLE
Cant get client_credentials grant to work

### ISSUE THREAD

**Issue by davenuk** [navikt/mock-oauth2-server#701]
i cant seem to get the `client_credentials` `grant_type` to work, either in code or using postman.
```
http://localhost:8888/default/token?grant_type=client_credentials&client_id=blur&client_secret=balh
```
grant_type is set in both headers and url but i get the same error

```
{
    "error_description": "missing required parameter grant_type",
    "error": "invalid_request"
}
```

[rfc6749#section-4.4.2](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2)
mentions about needing authorization - the code i am attempting to test works ok on a live system with no additional steps.

any help gratefully received

**Comment by davenuk** [comment]
additionally, i'm running mock-oauth2 in it's docker container.

**Comment by tronghn** [comment]
Which version of mock-oauth2-server are you running? Do you have any samples of the code that fails?

This works fine on my machine using the latest version (2.1.6):

```shell
curl -X POST 'http://localhost:8080/default/token' \
  -H "Content-Type: application/x-www-form-urlencoded" \
  --data-urlencode 'grant_type=client_credentials' \
  --data-urlencode 'client_id=some-client-id' \
  --data-urlencode 'client_secret=some-client-secret'
```

**Comment by tommytroen** [comment]
@davenuk It seems like you are trying to send the parameters as url parameters? The request needs to be a post with content-type `x-www-form-urlencoded` and the parameters in the post body.

**Comment by davenuk** [comment]
ok thank you both, i got postman working by using the body and x-www-form-urlencoded on 2.1.7.

this is the code that runs successfully against a live SAP server, its using ServiceStack.JsonServiceClient -
```
 var requestParams = new Dictionary<string, string>
                {
//the call requires a request dto even if empty
                    //{ "grant_type", configuration.OAuth2GrantType },
                    //{ "client_id", configuration.OAuth2ClientId },
                    //{ "client_secret", configuration.OAuth2ClientSecret },
                };
               
                var tokenClient = new JsonServiceClient(configuration.OAuth2TokenURL);
                tokenClient.AlwaysSendBasicAuthHeader = true;
                tokenClient.UserName = configuration.OAuth2ClientId;
                tokenClient.Password = configuration.OAuth2ClientSecret;
            
                var tokenResponse = tokenClient.Post<TokenResponse>(string.Format("{1}?grant_type={0}", configuration.OAuth2GrantType, configuration.OAuth2TokenURL), requestParams);
```
is it an unusual implementation by SAP?

**Comment by davenuk** [comment]
pebkac
