### ISSUE TITLE
Transitive dependency netty-all is not needed?

### ISSUE THREAD

**Issue by jarlah** [navikt/mock-oauth2-server#721]
I started using the mock server and i noticed i could not run the application itself when adding mock server without adding netty-codec and netty-resolver. I found out that mock server includes a transitive netty-all dependency, which i excluded and problem solved. But why does it affect runtime ? I think this is a two fold question:

1. Why is mock server including netty-all and why is not needed (why can i exclude it)
2. Why is maven so.... donkey :stuck_out_tongue_winking_eye: 

i had to do this in our project

```xml
        <dependency>
            <groupId>no.nav.security</groupId>
            <artifactId>mock-oauth2-server</artifactId>
            <version>${mock-oauth2-server.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-all</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

propably because we had another dependency that brought in 

```
INFO] |  |  +- org.springframework.boot:spring-boot-starter-reactor-netty:jar:3.2.4:compile
[INFO] |  |  |  \- io.projectreactor.netty:reactor-netty-http:jar:1.1.17:compile
[INFO] |  |  |     \- io.projectreactor.netty:reactor-netty-core:jar:1.1.17:compile
```

I guess? 

But question about why i can exclude it and it still works, is still valid

**Comment by ybelMekk** [comment]
All is not needed, but could do the same with this: https://github.com/navikt/mock-oauth2-server/pull/723 @jarlah

**Comment by jarlah** [comment]
it works perfectly @ybelMekk. Just started using the new version 2.1.9 in two repos and I could finally remove the exclusions for netty. 🙌
