### ISSUE TITLE
docker pull throwing " no basic auth credentials " error

### ISSUE THREAD

**Issue by mariomartinezricston** [navikt/mock-oauth2-server#8]
Hi, 

I am trying to run the mock Oauth server through a docker container. When pulling the docker image, I am receiving a "no basic auth credentials" error.

Command executed: _**docker pull docker.pkg.github.com/navikt/mock-oauth2-server/mock-oauth2-server:0.1.35**_

Output: **Error response from daemon: Get https://docker.pkg.github.com/v2/navikt/mock-oauth2-server/mock-oauth2-server/manifests/0.1.35: no basic auth credentials**

**Comment by mariomartinezricston** [comment]
After login successfully into docker.pkg.github.com using the command:   docker login https://docker.pkg.github.com -u $USERNAME

I am now receiving: `**_Error response from daemon: unauthorized: Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured._**`

**Comment by mariomartinezricston** [comment]
Found the solution, the docker.pkg.github.com authorization does not support account password. Instead, a "personal access token" value has to be given when executing `docker login https://docker.pkg.github.com -u $USERNAME`

**Comment by jksolbakken** [comment]
Good to see that you found a solution! We should probably move this image to the new `Github Container Registry` which allows for anonymous pulling.

**Comment by TheEYL** [comment]
> Good to see that you found a solution! We should probably move this image to the new `GitHub Container Registry` which allows for anonymous pulling.

I second this motion.
